config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
      resources :products do
        get 'add_on_erp_variants' => 'add_on_erp_variants#index'
        resources :variants do
          resources :add_on_erp_variants do
        end
      end
    end
  end
end

app/models/spree/ability_decorator.rb
class AbilityDecorator
  include CanCan::Ability
  def initialize(user)

    if user.respond_to?(:has_spree_role?) && user.has_spree_role?('admin')
      can [:admin, :index, :read, :update, :edit], Spree::AddOnErpVariant
    end
  end
end

Spree::Ability.register_ability(AbilityDecorator)

app/models/spree/add_on_erp_variant.rb
module Spree
  class AddOnErpVariant < ActiveRecord::Base
    belongs_to :variant, class_name: 'Spree::Variant', :foreign_key => :variant_id
    belongs_to :product, class_name: 'Spree::Product'

    validates :erp_product_code, length: {maximum: 32}, allow_nil: true
    validates :stock,      numericality: { only_integer: true }, allow_nil: true

  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
  has_many :add_on_erp_variants, :through => :variants


#   enable products to CRUD each own add_on_maker_variants by accept nesting as child
  accepts_nested_attributes_for :add_on_erp_variants, allow_destroy: true
  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    has_one :add_on_erp_variant, class_name: 'Spree::AddOnErpVariant'

#   builds add_on_maker_variants from created variant ids
    after_create :create_add_on_erp_variants_from_variants

#   enable variants to CRUD each own add_on_maker_variants by accept nesting as child
    accepts_nested_attributes_for :add_on_erp_variant, allow_destroy: true

    def create_add_on_erp_variants_from_variants
      Spree::AddOnErpVariant.where(variant_id: self.id).first_or_initialize do |a|
        a.variant_id = self.id
        a.save!
      end
    end

  end
end

app/controllers/spree/admin/add_on_erp_variants_controller.rb
module Spree
  module Admin
    class AddOnErpVariantsController < ResourceController
      before_filter :load_data, :except => :index

      def show
        session[:return_to] ||= request.referer
        redirect_to( :action => :edit )
      end

      def index
logger.info "###############index#####################"
        session[:return_to] = request.url
        @product = Spree::Product.find_by_permalink!(params[:product_id])
logger.info "@product.inspect"
logger.info @product.variants.inspect
        if @product.has_variants?
          @variant = @product.variants
        else
          @variant = Spree::Variant.where(:id => @product.master.id)
        end
logger.info "@variant"
logger.info @variant.inspect
        @add_on_erp_variant = Spree::AddOnErpVariant.where(:variant_id => @variant).page(params[:page])
logger.info "@add_on_erp_variant"
logger.info @add_on_erp_variant.inspect
        render :index
      end

      def edit
logger.info "###############edit#####################"
        session[:return_to] = request.url
        @product = Spree::Product.find_by_permalink!(params[:product_id])
        @add_on_erp_variant = Spree::AddOnErpVariant.where(:variant_id => params[:variant_id]).first_or_initialize
        logger.info "@add_on_erp_variant.inspect"
        logger.info @add_on_erp_variant.inspect
        render :edit
      end

      def create
        @add_on_erp_variant = Spree::AddOnErpVariant.new(add_on_erp_variant_params.merge(:variant_id => params[:variant_id]))

        respond_to do |format|
          if @add_on_erp_variant.save
            flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_created')
            format.html { redirect_to admin_product_variant_add_on_erp_variants_path }
            format.json { render action: 'index', status: :created, location: @add_on_erp_variant }
          else
            flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_has_error')
            format.html { render action: 'new' }
            format.json { render json: @add_on_erp_variant.errors }
          end
        end
      end

      def update
        respond_to do |format|
          if @add_on_erp_variant.update(add_on_erp_variant_params)
            flash[:success] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_updated')
            format.html { redirect_to :action => :index }
            format.json { head :no_content }
          else
            flash[:error] = t('add_on.notice_messages.admin_product_variant_add_on_maker_variant_has_error')
            format.html { render action: 'edit' }
            format.json { render json: @add_on_erp_variant.errors }
          end
        end
      end

      def destroy
        @variant = Spree::Variant.find(params[:id])
        if @variant.destroy
          flash[:success] = Spree.t('notice_messages.variant_deleted')
        else
          flash[:success] = Spree.t('notice_messages.variant_not_deleted')
        end

        respond_with(@variant) do |format|
          format.html { redirect_to admin_product_erp_variant_path(params[:product_id]) }
          format.js  { render_js_for_destroy }
        end
      end

  protected
      def variant_includes
        [:add_on_erp_variants]
      end

      def load_data
      @product = Spree::Product.find_by_permalink!(params[:product_id])
        @taxons = Taxon.order(:name)
        @option_types = OptionType.order(:name)
        @tax_categories = TaxCategory.order(:name)
        @shipping_categories = ShippingCategory.order(:name)
      end

  private
      def permit_attributes
        params.require(:add_on_erp_variant).permit!
      end

      def add_on_erp_variant_params
        params.require(:add_on_erp_variant).permit(:variant_id, :erp_product_code, :stock)
      end
    end
  end
end

app/views/spree/admin/add_on_erp_variants/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Erp Variants'} %>

<% content_for :page_title do %>
  : <%= @add_on_erp_variant.variant.sku %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_maker_variants_list'), admin_product_add_on_erp_variants_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= form_for [:admin, @product, @variant, @add_on_erp_variant], url: admin_product_variant_add_on_erp_variant_path(:variant_id => params[:variant_id], :id => params[:id]) do |f| %>
  <div data-hook="admin_inside_add_on_erp_variant_form" class="row">
    <div class='alpha six columns'>
      <div class='field'>
    <%= f.field_container :erp_product_code do %>
          <%= f.label :erp_product_code, t('activerecord.attributes.add_on_erp_variant.erp_product_code') %><br />
          <%= f.text_field :erp_product_code, :class => 'fullwidth' %>
          <%= f.error_message_on :erp_product_code %>
    <% end %>
      </div>
      <div class='field'>
    <%= f.field_container :stock do %>
        <%= f.label :stock, t('activerecord.attributes.add_on_erp_variant.stock') %>
        <%= f.text_field :stock, :class => 'fullwidth' %>
        <%= f.error_message_on :stock %>
    <% end %>
      </div>
    </div>

    </div>


      <%= f.submit %>

  </div>
<% end %>

app/views/spree/admin/add_on_erp_variants/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Erp Variants'} %>

<% content_for :page_title do %>
  <%= t("add_on.listing_add_on_erp_variant") %>
<% end %>

<%= paginate @add_on_erp_variant %>

<table class='index'>
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.variant.id") %></th>
      <th><%= Spree.t(:options) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:sku) %></th>
    </tr>
  </thead>
  
  <tbody>
    <% for variant in @variant %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="align-center"><%= variant.id %></td>
        <td class="align-center"><%= variant.options_text %></td>
        <td class="align-center"><%= variant.price %></td>
        <td class="align-center"><%= variant.sku %></td>

        <% if variant.add_on_erp_variant.blank? %>
        <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_erp_variants/new") , :class => 'edit' %></td>
        <% else %>
        <td class="actions"><%= link_to t("edit"), ("/admin/products/" + params[:product_id] + "/variants/#{variant.id}/add_on_erp_variants/#{variant.add_on_erp_variant.id}/edit") , :class => 'edit' %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/add_on_erp_variants/new.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Add On Erp Variants'} %><% content_for :page_title do %>
  <%= t('add_on.add_on_erp_variant') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('add_on.back_to_product_add_on_erp_variants_list'), admin_product_add_on_erp_variants_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= form_for [:admin, @product, @variant, @add_on_erp_variant], url: admin_product_variant_add_on_erp_variants_path(:variant_id => params[:variant_id]) do |f| %>
  <div data-hook="admin_inside_add_on_erp_variant_form" class="row">
    <div class='alpha six columns'>
      <div class='field'>
    <%= f.field_container :erp_product_code do %>
          <%= f.label :erp_product_code, t('activerecord.attributes.add_on_erp_variant.erp_product_code') %><br />
          <%= f.text_field :erp_product_code, :class => 'fullwidth' %>
          <%= f.error_message_on :erp_product_code %>
    <% end %>
      </div>
      <div class='field'>
    <%= f.field_container :stock do %>
        <%= f.label :stock, t('activerecord.attributes.add_on_erp_variant.stock') %>
        <%= f.text_field :stock, :class => 'fullwidth' %>
        <%= f.error_message_on :stock %>
    <% end %>
      </div>
    </div>

    </div>


      <%= f.submit %>

  </div>
<% end %>